# joint_limits.yaml allows the dynamics properties specified in the URDF to be overwritten or augmented as needed
# Specific joint properties can be changed with the keys [max_position, min_position, max_velocity, max_acceleration]
# Joint limits can be turned off with [has_velocity_limits, has_acceleration_limits]
joint_limits:
  inner_joint:
    has_velocity_limits: true
    max_velocity: 6.737
    has_acceleration_limits: false
    max_acceleration: 0
  outer_joint:
    has_velocity_limits: true
    max_velocity: 12.5664
    has_acceleration_limits: false
    max_acceleration: 0
  quill_prismatic_joint:
    has_velocity_limits: true
    max_velocity: 1.1
    has_acceleration_limits: false
    max_acceleration: 0
  quill_rotation_joint:
    has_velocity_limits: true
    max_velocity: 20.944
    has_acceleration_limits: false
    max_acceleration: 0